### ISSUE TITLE
Crash when trying to create lxc container

### ISSUE THREAD

**Issue by jwallden** [Telmate/terraform-provider-proxmox#252]
I'm trying to create an lxc container using the lxc_example.tf as a base. When running `terraform apply` it crashes with

> Error: rpc error: code = Unavailable desc = transport is closing

Terraform v0.13.5
+ provider registry.terraform.io/telmate/proxmox v2.6.4

[main.txt](https://github.com/Telmate/terraform-provider-proxmox/files/5539687/main.txt) (tf-file)

[crash.log](https://github.com/Telmate/terraform-provider-proxmox/files/5539685/crash.log)

**Comment by trilom** [comment]
Same issue for me on terraform v0.13.5 and plugin v2.6.5 using basically the default example.

**Comment by trilom** [comment]
I was able to work past this by starting at the default example that alters the "features" portion.

When I reverted back to the earliest built version (v2.6.1) I had the same issue as above.  I found PR #236 that seems to have some recent changes to the rootfs resource for LXC so I started there.

By explicitly adding to point to my ceph mount:
```
    rootfs {
      storage = "rep_1g"
      size = "8G"
    }
```
I received the following which seemed way "healthier" than the previous jargon, after switching my provider user to root I was able to create the container and get past this limitation on v2.6.5.  It does stand to mention that the default functionality of "rootfs just working" doesn't seem to just work without this explicit stanza above and it should be mentioned, or removed from the example to use the features by default as this might add complexity for those not using the root user as their terraform user.  Please let me know if you need anything else, thank you for your hammers you've made.
```
Error: Error creating LXC container: 403 Permission check failed (changing feature flags is only allowed for root@pam), error status: {"data":null} (params: {"arch":"amd64","cmode":"tty","console":true,"cpulimit":0,"cpuunits":1024,"features":"nesting=1,keyctl=1","hostname":"terraform-new-container","memory":512,"net0":"name=eth0,ip=10.1.1.20/24,tag=20,ip6=dhcp,bridge=vmbr0,gw=10.1.1.1","onboot":false,"ostemplate":"cephfs:vztmpl/debian-10-standard_10.5-1_amd64.tar.gz","password":"ubuntu","pool":"default","protection":false,"rootfs":"rep_1g:8","start":false,"storage":"local","swap":512,"tags":"","tty":2,"unprivileged":true,"vmid":107})
```
```hcl
provider "proxmox" {
    pm_tls_insecure = true
    pm_api_url = "https://pve:8006/api2/json"
    pm_password = "passwrd"
    pm_user = "root@pam"
}

resource "proxmox_lxc" "lxc-test" {
    features {
        nesting = true
        keyctl = true
    }
    hostname = "terraform-new-container"
    rootfs {
      storage = "rep_1g"
      size = "8G"
    }
    network {
        name = "eth0"
        bridge = "vmbr0"
        ip = "10.1.1.10/24"
        gw = "10.1.1.1"
        ip6 = "dhcp"
        tag = "20"
        firewall = false
    }
    ostemplate = "cephfs:vztmpl/debian-10-standard_10.5-1_amd64.tar.gz"
    password = "ubuntu"
    pool = "default"
    target_node = "h2c"
    unprivileged = true
}
```

**Comment by remyd1** [comment]
Same error here. @trilom solution worked for me.

Thanks.

**Comment by jwallden** [comment]
@trilom thing worked for me as well. Thank you. 
However, I still think this is a bug that should be fixed. Either there should be default values for storage and volume keys or it should fail in a more graceful way and also be stated in the example.

**Comment by KnKay** [comment]
Same here! 

The fixworked for me as well. 
Maybe a small fix would be adopting the example!

**Comment by danfmihai** [comment]
I'm using v.2.9.1 and Terraform v1.0.10 and wanted to try to add **_features_** and got the same error like everybody. Then I removed the features in the code, tried to do `terraform apply` again and keep getting the same error ...`"cpuunits":1024,"features":"","` and **features** still shows in error code. Deleted .terraform folders and files created and tried again same error. Can't get rid of this error now, even though I don't even have features enabled or added to my code. I'm using root@pam with token. Plugin "proxmox_lxc" worked fine until I added features into code. Here's how the error looks like

` Error: Error creating LXC container: 403 Permission check failed, error status: {"data":null} (params: {"arch":"amd64","cmode":"tty","console":true,"cores":2,"cpulimit":0,"cpuunits":1024,"**features**":"","hostname":"bastion-ubuntu-1","memory":2048,"net0":"bridge=vmbr0,name=eth0,gw=192.168.102.1,ip=192.168.102.170/24","onboot":true,"ostemplate":"piso:vztmpl/ubuntu-21.04-standard_21.04-1_amd64.tar.gz","password":"pass","protection":false,"rootfs":"nvme:15","start":true,"storage":"local","swap":0,"tags":"","tty":2,"unprivileged":true,"vmid":109})
│ 
│   with proxmox_lxc.basic[0],
│   on c2-main.tf line 11, in resource "proxmox_lxc" "basic":
│   11: resource "proxmox_lxc" "basic" {`

**Comment by danfmihai** [comment]
I noticed if I use `root@pam` as user and `pm_password` instead of `pm_api_token_id` it creates the LXC with features nesting and keyctl...

**Comment by scibi** [comment]
@danfmihai make sure you unchecked "Privilege separation" when creating token in Proxmox:

![image](https://user-images.githubusercontent.com/703860/146422554-69426f05-1027-44ed-a802-0ae3e904e22c.png)

or grant permissions to token not the user:

```
root@pve1:~# pveum acl mod / --tokens 'terraform-prov@pve!terraform' --roles TerraformProv
```

It should be mentioned in docs. I've spent way too many hours trying to debug exactly this error ;)
